version: '3.8'
services:
  sqlserver_arq_capas:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bd_arq_capas
    restart: always
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
    volumes:
      - E:\Docker\Volumenes\sqlserver_data_arq_capas:/var/opt/mssql/data
    ports:
      - 1402:1433